# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GB_Map_SA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


	pod 'GoogleMaps'
  # Pods for GB_Map_SA

end
